# Generated by Django 2.2.2 on 2019-07-25 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_auto_20190725_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='check_in',
            new_name='date',
        ),
    ]
